apiVersion: batch/v1
kind: Job
metadata:
  name: api-migrations
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrations
        image: api-image:latest
        env:
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: connection
